login:
    user: "SPIGOT_USER"
    password: "SPIGOT_PASSWORD"
    # 2fa method, totp or email
    2fa_provider: "totp"

# the profile post id that purchasers need to like
profile_post_id: 196759

discord_api_token: "TOKEN"
guild_id: 330725294749122561

channels:
    buy_log: 927349992836960348
    verify_log: 927339823553978468

roles:
    resources:
        # spigot_resource_id : discord_role_name
        9732: "SafariNet"
        40527: "AdvancedOreGen"
        60331: "DropEdit"
    premium:
        - "Premium"
        - "Premium+"
